const express = require('express');
const { Op } = require('sequelize');
const { authMiddleware } = require('../middleware/auth');
const { cache } = require('../config/redis');
const router = express.Router();

// GET /facturas - listar facturas
router.get('/', authMiddleware, async (req, res) => {
  try {
      const { fecha_inicio, fecha_fin, estado, zona, limit = 50, offset = 0 } = req.query;
          const cacheKey = `facturas:${JSON.stringify(req.query)}`;
              const cached = await cache.get(cacheKey);
                  if (cached) return res.json(cached);

                      // Simulacion de datos
                          const facturas = [];
                              const estados = ['pagado', 'pendiente', 'cancelado'];
                                  const zonas = ['Zona Norte', 'Zona Sur', 'Zona Centro', 'Zona Este', 'Zona Oeste'];
                                      for (let i = 1; i <= 20; i++) {
                                            facturas.push({
                                                    id: i,
                                                            numero_factura: `F-${String(i).padStart(5,'0')}`,
                                                                    cajero: 'Admin',
                                                                            cliente: `Cliente ${i}`,
                                                                                    usuario: `user${i}`,
                                                                                            fecha_emision: new Date(Date.now() - i * 86400000).toISOString().split('T')[0],
                                                                                                    fecha_pago: i % 3 !== 0 ? new Date(Date.now() - i * 86400000 + 3600000).toISOString().split('T')[0] : null,
                                                                                                            estado: estados[i % 3],
                                                                                                                    zona: zonas[i % 5],
                                                                                                                            forma_pago: i % 2 === 0 ? 'Efectivo' : 'Transferencia',
                                                                                                                                    referencia: i % 2 === 0 ? null : `REF-${i}`,
                                                                                                                                            total: (Math.random() * 500 + 100).toFixed(2)
                                                                                                                                                  });
                                                                                                                                                      }
                                                                                                                                                      
                                                                                                                                                          const result = { count: facturas.length, rows: facturas.slice(offset, offset + limit) };
                                                                                                                                                              await cache.set(cacheKey, result, 60);
                                                                                                                                                                  res.json(result);
                                                                                                                                                                    } catch (error) {
                                                                                                                                                                        res.status(500).json({ error: error.message });
                                                                                                                                                                          }
                                                                                                                                                                          });
                                                                                                                                                                          
                                                                                                                                                                          // GET /facturas/pendientes
                                                                                                                                                                          router.get('/pendientes', authMiddleware, async (req, res) => {
                                                                                                                                                                            try {
                                                                                                                                                                                const { limit = 50, offset = 0 } = req.query;
                                                                                                                                                                                    const pendientes = [];
                                                                                                                                                                                        for (let i = 1; i <= 30; i++) {
                                                                                                                                                                                              pendientes.push({
                                                                                                                                                                                                      id: i,
                                                                                                                                                                                                              numero_factura: `F-${String(i).padStart(5,'0')}`,
                                                                                                                                                                                                                      cliente: `Cliente ${i}`,
                                                                                                                                                                                                                              id_servicio: `SVC-${i}`,
                                                                                                                                                                                                                                      estado_servicio: i % 3 === 0 ? 'suspendido' : 'activo',
                                                                                                                                                                                                                                              zona: `Zona ${i % 5 + 1}`,
                                                                                                                                                                                                                                                      monto: (Math.random() * 300 + 50).toFixed(2),
                                                                                                                                                                                                                                                              fecha_vencimiento: new Date(Date.now() - i * 86400000).toISOString().split('T')[0]
                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                            res.json({ count: pendientes.length, rows: pendientes.slice(offset, offset + limit) });
                                                                                                                                                                                                                                                                              } catch (error) {
                                                                                                                                                                                                                                                                                  res.status(500).json({ error: error.message });
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                    // GET /facturas/promesas-pago
                                                                                                                                                                                                                                                                                    router.get('/promesas-pago', authMiddleware, async (req, res) => {
                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                          const promesas = [];
                                                                                                                                                                                                                                                                                              for (let i = 1; i <= 10; i++) {
                                                                                                                                                                                                                                                                                                    promesas.push({
                                                                                                                                                                                                                                                                                                            id: i,
                                                                                                                                                                                                                                                                                                                    numero_factura: `F-${String(i).padStart(5,'0')}`,
                                                                                                                                                                                                                                                                                                                            creado_por: 'Admin',
                                                                                                                                                                                                                                                                                                                                    cliente: `Cliente ${i}`,
                                                                                                                                                                                                                                                                                                                                            ip: `192.168.1.${i}`,
                                                                                                                                                                                                                                                                                                                                                    creado: new Date(Date.now() - i * 86400000).toISOString(),
                                                                                                                                                                                                                                                                                                                                                            fecha_limite: new Date(Date.now() + i * 86400000).toISOString().split('T')[0],
                                                                                                                                                                                                                                                                                                                                                                    monto: (Math.random() * 300 + 50).toFixed(2)
                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                  res.json({ count: promesas.length, rows: promesas });
                                                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                        res.status(500).json({ error: error.message });
                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                          // GET /facturas/estadisticas
                                                                                                                                                                                                                                                                                                                                                                                          router.get('/estadisticas', authMiddleware, async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                const meses = ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'];
                                                                                                                                                                                                                                                                                                                                                                                                    const data = meses.map((mes, i) => ({
                                                                                                                                                                                                                                                                                                                                                                                                          mes,
                                                                                                                                                                                                                                                                                                                                                                                                                ingresos: Math.floor(Math.random() * 500000 + 100000),
                                                                                                                                                                                                                                                                                                                                                                                                                      gastos: Math.floor(Math.random() * 100000 + 20000),
                                                                                                                                                                                                                                                                                                                                                                                                                            clientes_nuevos: Math.floor(Math.random() * 30 + 5)
                                                                                                                                                                                                                                                                                                                                                                                                                                }));
                                                                                                                                                                                                                                                                                                                                                                                                                                    res.json(data);
                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                          res.status(500).json({ error: error.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                            // POST /facturas/registrar-pago
                                                                                                                                                                                                                                                                                                                                                                                                                                            router.post('/registrar-pago', authMiddleware, async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  const { factura_id, monto, forma_pago, referencia, fecha_pago } = req.body;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      const pago = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            id: Date.now(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  factura_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        monto,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              forma_pago,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    referencia,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fecha_pago: fecha_pago || new Date().toISOString().split('T')[0],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                registrado_por: req.user.username,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      created_at: new Date().toISOString()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await cache.delPattern('facturas:*');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.status(201).json(pago);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.status(500).json({ error: error.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          module.exports = router;
